version: '2'
services:
  nginx:
    build: .
    ports:
      - "80:80"
    links:
      - fpm
    depends_on:
      - fpm
  fpm:
    image: drupal:7.50-fpm
    environment:
      - MYSQL_DATABASE=drupal
    links:
      - mysql:mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
